### ISSUE TITLE
Official support for Python 3.11 and Python 3.12?

### ISSUE THREAD

**Issue by bartelemi** [Kludex/mangum#317]
AWS Lambda officially supports Python 3.11 and Python 3.12.

Would it be possible to test this library against those 2 new versions of Python?
From the setup.py it looks like there is no constraint preventing us from using it with runtimes higher than 3.10, however it's not tested.

**Comment by 25thbamofthetower** [comment]
The tests are failing in the Github actions because of 3.7 and the linting steps. I forked and added 3.11 and 3.12 to the test.yml, and commented out the previous two, and they passed.

**Comment by Kludex** [comment]
Added explicit support to Python 3.13. 👍
