### ISSUE TITLE
mangum.io Domain Expired

### ISSUE THREAD

**Issue by jglien** [Kludex/mangum#322]
I know this might not be the right place for this, but the docs site domain has expired and the site is down.

edit: this implies that this project may have been abandoned. For others looking for the doc site and finding this go here https://github.com/jordaneremieff/mangum/blob/main/docs/index.md

**Comment by kailukowiak** [comment]
> edit: this implies that this project may have been abandoned. 

@jglien, Do you know of any alternatives that exist? I see some but most of the ones I search for are using Mangum on the backend. I guess I could use [AWS Lambda Powertools](https://docs.powertools.aws.dev/lambda/python/latest/) but it is really nice having local development/testing on fastapi and then wrapping the app in a handler.

**Comment by jglien** [comment]
> > edit: this implies that this project may have been abandoned.
> 
> @jglien, Do you know of any alternatives that exist? I see some but most of the ones I search for are using Mangum on the backend. I guess I could use [AWS Lambda Powertools](https://docs.powertools.aws.dev/lambda/python/latest/) but it is really nice having local development/testing on fastapi and then wrapping the app in a handler.

The official solution provided by AWS is [AWS Lambda Web Adapter](https://github.com/awslabs/aws-lambda-web-adapter). However, this is just something that sits in front of your web app and forwards requests, it doesn't run as part of your app like Mangum.

**Comment by jglien** [comment]
> > edit: this implies that this project may have been abandoned.
> 
> @jglien, Do you know of any alternatives that exist? I see some but most of the ones I search for are using Mangum on the backend. I guess I could use [AWS Lambda Powertools](https://docs.powertools.aws.dev/lambda/python/latest/) but it is really nice having local development/testing on fastapi and then wrapping the app in a handler.

> > edit: this implies that this project may have been abandoned.
> 
> @jglien, Do you know of any alternatives that exist? I see some but most of the ones I search for are using Mangum on the backend. I guess I could use [AWS Lambda Powertools](https://docs.powertools.aws.dev/lambda/python/latest/) but it is really nice having local development/testing on fastapi and then wrapping the app in a handler.

@kailukowiak The official solution provided by AWS is [AWS Lambda Web Adapter](https://github.com/awslabs/aws-lambda-web-adapter). However, this is just something that sits in front of your web app and forwards requests, it doesn't run as part of your app like Mangum.

**Comment by lukewiwa** [comment]
Looks like the domain has been picked up by someone else and had AI blog spam dumped in there.

**Comment by kailukowiak** [comment]
@lukewiwa I hope they are at least using Mangum to run the blog 🤣

**Comment by Kludex** [comment]
Someone bought the domain?

**Comment by jbsilva** [comment]
> I'll fix during the weekend.

@Kludex I'm really happy that you adopted this repo!
I was worried that the project would die.

**Comment by Kludex** [comment]
> > I'll fix during the weekend.
> 
> @Kludex I'm really happy that you adopted this repo! I was worried that the project would die.

Bora Brasil! 😎 👍

**Comment by Kludex** [comment]
Mangum lives under http://mangum.fastapiexpert.com/ now.

**Comment by kailukowiak** [comment]
Thanks, I really appreciate you taking this project on. I use it all the time and love it. (But am in no way qualified to maintain). 

Thanks
