### ISSUE TITLE
Support lifespan state

### ISSUE THREAD

**Issue by FurqanHabibi** [Kludex/mangum#323]
FastAPI version [0.94.0](https://github.com/tiangolo/fastapi/releases/tag/0.94.0) and Starlette version [0.26.0](https://github.com/encode/starlette/releases/tag/0.26.0) have added support for lifespan state.

Other ASGI server implementation like uvicorn have added support as well.

Reference:
https://asgi.readthedocs.io/en/latest/specs/lifespan.html#lifespan-state

**Comment by Kludex** [comment]
This is now supported.
